services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      # 소스 코드 양방향 마운트 → 저장 시 즉시 반영
      - .:/app
      # Maven 캐시 볼륨 → 빌드 속도 향상
      - maven-cache:/root/.m2
    # spring-boot:run 사용
    ports:
      - "18080:8080"
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.fork=false
volumes:
  maven-cache: