server:
  port: ${PORT:8080}

spring:
  devtools:
    restart:
      additional-paths: src/main/java, src/main/resources
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
